---
# tasks file for ceph-admin

- name: Generate ssh key
  command: "ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa"

- name: Copy ssh id to ceph-nodes
  command: "sshpass -p 'vagrant' ssh-copy-id -o StrictHostKeyChecking=no vagrant@{{ item }}"
  with_items: "{{ groups['ceph_nodes'] }}"

- name: Install dependency packages
  become: true
  become_user: root
  become_method: sudo
  yum:
    name:
      - ceph-deploy
      - python-setuptools
    state: installed

- name: Install ceph stable release
  command: "ceph-deploy install --release nautilus {{ groups['ceph_nodes'] | join(' ') }}"

- name: Create state directory
  file:
    path: ~/ceph-cluster
    state: directory

- name: Create a cluster
  command: "{{ item }} chdir=~/ceph-cluster"
  with_items:
    - "ceph-deploy new {{ groups['ceph_nodes'] | join(' ') }}"

- name: Deploy the initial monitor and gather the keys
  command: "{{ item }} chdir=~/ceph-cluster"
  with_items:
    - "ceph-deploy mon create-initial"

- name: Copy the conf file and admin key to your admin node and ceph nodes
  command: "{{ item }} chdir=~/ceph-cluster"
  with_items:
    - "ceph-deploy admin {{ groups['ceph_nodes'] | join(' ') }}"

- name: Deploy a manager daemon
  command: "{{ item }} chdir=~/ceph-cluster"
  with_items:
    - "ceph-deploy mgr create {{ groups['ceph_nodes'][0] }}"

- name: Create metadata servers
  command: "{{ item }} chdir=~/ceph-cluster"
  with_items:
    - "ceph-deploy mds create {{ groups['ceph_nodes'] | join(' ') }}"

- name: Create OSDs
  command: "ceph-deploy osd create --data /dev/vdb {{ item }} chdir=~/ceph-cluster"
  with_items: "{{ groups['ceph_nodes'] }}"
